# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Experiments Never Fail
email: okuokuoku[at]gmail.com
description: >
  Try and try again
logo: "/assets/images/logo.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.amay077.net" # the base hostname & protocol for your site

permalink: /blog/:year/:month/:day/:title/

paginate:	10 # The number of posts to show per page on your homepage

name: 'amay077'
bio: >
  Microsoft MVP(Xamarin). フルリモートワーカー. Geospatial Mobile app developer. Love C#.
author_image: "/assets/images/author.png"
twitter_username: amay077
github_username:  amay077

# Build settings
markdown: kramdown
kramdown:
  input: KramdownEasyLink
  hard_wrap: true
  parse_block_html: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: false

# Disqus Comments
disqus_short_name: experimentsneverfail

# Google Analytics
google_analytics_tracking_id: UA-224332-7

gems:
  - jekyll-paginate
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - deploy.sh
  - CNAME