version: '3.1'
services:
  eleventy-build:
    image: node:12.16.2
    container_name: eleventy-build
    restart: always
    volumes:
      - ./:/work
    working_dir: "/work"
    command: bash -c "npm ci && npm run build"
